within ;
package MMChvdcLibrary "Modular Multilevel Coverter HVDC Library."
  annotation (uses(
      Modelica(version="4.1.0"),
      OpenIPSL(version="3.1.0"),
      Complex(version="4.1.0")),
    Documentation(info="<html>
<p>The MMChvdcLibrary or Modular Multilevel Coverter HVDC Library is a <a href=\"https://modelica.org/\">Modelica</a> library, developed and maintained by the <a href=\"https://alsetlab.github.io/\">ALSETLab</a> research group, collaborators and friends (contributions are welcome!). The library contains a set of component models and test MMC HVDC system networks adopting the phasor modeling approach.</p>
</html>"),
    Icon(graphics={
        Rectangle(
          extent={{-100,100},{100,-100}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={215,215,215},
          fillPattern=FillPattern.Solid,
          radius=20),
        Line(
          points={{-14,10},{14,10}},
          color={0,0,0},
          thickness=0.5),
        Line(
          points={{-14,-10},{14,-10}},
          color={0,0,0},
          thickness=0.5),
        Line(
          points={{-90,0},{-80,0}},
          color={0,0,0},
          thickness=0.5),
        Line(
          points={{80,0},{90,0}},
          color={0,0,0},
          thickness=0.5),
        Rectangle(
          extent={{14,40},{80,-40}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={135,135,135},
          fillPattern=FillPattern.Solid),
        Polygon(
          points={{32,-10},{46,10},{60,-10},{32,-10}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Line(
          points={{46,-20},{46,-10}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{46,10},{46,20}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{34,10},{58,10}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{46,10},{58,16}},
          color={0,0,0},
          thickness=1),
        Rectangle(
          extent={{-80,40},{-14,-40}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={135,135,135},
          fillPattern=FillPattern.Solid),
        Polygon(
          points={{-30,-60},{-30,-60}},
          lineColor={0,0,0},
          lineThickness=0.5,
          smooth=Smooth.Bezier),
        Polygon(
          points={{-62,-10},{-48,10},{-34,-10},{-62,-10}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Line(
          points={{-48,-20},{-48,-10}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{-48,10},{-48,20}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{-60,10},{-36,10}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{-48,10},{-36,16}},
          color={0,0,0},
          thickness=1)}));
end MMChvdcLibrary;
