within MMC_HVDC_AMCONF2026;
package MMC_HVDCstation "Different modes of operation of the MMC HVDC station."

  annotation (Icon(graphics={
        Rectangle(
          extent={{-100,100},{100,-100}},
          lineColor={0,0,0},
          lineThickness=0.5),
        Rectangle(
          extent={{-100,100},{100,-60}},
          lineColor={0,0,0},
          lineThickness=0.5),
        Line(
          points={{-100,-60},{100,100}},
          color={0,0,0},
          thickness=0.5),
        Line(
          points={{-50,52},{-30,52}},
          color={0,0,0},
          thickness=1),
        Line(
          points={{-50,40},{-30,40}},
          color={0,0,0},
          thickness=1),
        Rectangle(
          extent={{-84,-70},{-72,-86}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Rectangle(
          extent={{-54,-70},{-42,-86}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Rectangle(
          extent={{-24,-70},{-12,-86}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Rectangle(
          extent={{12,-70},{24,-86}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Rectangle(
          extent={{42,-70},{54,-86}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Rectangle(
          extent={{72,-70},{84,-86}},
          lineColor={0,0,0},
          lineThickness=0.5,
          fillColor={0,0,0},
          fillPattern=FillPattern.Solid),
        Line(
          points={{30,0},{40,10},{50,0},{60,-10},{70,0}},
          color={0,0,0},
          thickness=1,
          smooth=Smooth.Bezier)}));
end MMC_HVDCstation;
