within MMC_HVDC_AMCONF2026.Information;
class Literature "Cited Papers"
  extends Modelica.Icons.References;
  annotation (Documentation(info="<html>
<ol>
<li><span style=\"font-family: Arial; font-size: 9pt;\"><a name=\"docs-internal-guid-0bb82733-7fff-5f34-f140-2aa13910c70a\">D</a><span style=\"color: #333333; background-color: #ffffff;\">. Jovcic and A. A. Jamshidifar, &quot;Phasor Model of Modular Multilevel Converter With Circulating Current Suppression Control,&quot; in <i>IEEE Transactions on Power Delivery</i>, vol. 30, no. 4, pp. 1889-1897, Aug. 2015, doi: 10.1109/TPWRD.2014.2372780.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">J. C. Gonzalez&ndash;Torres, R. Mourouvin, K. Shinoda, A. Zama and A. Benchaib, &quot;A simplified approach to model grid-forming controlled MMCs in power system stability studies,&quot; <i>2021 IEEE PES Innovative Smart Grid Technologies Europe (ISGT Europe)</i>, Espoo, Finland, 2021, pp. 01-06, doi: 10.1109/ISGTEurope52324.2021.9640024.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">J. Freytes, L. Papangelis, H. Saad, P. Rault, T. Van Cutsem and X. Guillaud, &quot;On the modeling of MMC for use in large scale dynamic simulations,&quot; <i>2016 Power Systems Computation Conference (PSCC)</i>, Genoa, Italy, 2016, pp. 1-7, doi: 10.1109/PSCC.2016.7540938.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">T. Larsson, A. Petersson, A. Edris, D. Kidd and F. Aboytes, &quot;Eagle Pass back-to-back tie: a dual purpose application of voltage source converter technology,&quot; <i>2001 Power Engineering Society Summer Meeting. Conference Proceedings (Cat. No.01CH37262)</i>, Vancouver, BC, Canada, 2001, pp. 1686-1691 vol.3, doi: 10.1109/PESS.2001.970329.</span></li>
<li><span style=\"font-family: Roboto; font-size: 9pt;\">Midtsund, T., Norway, Becker, A., Karlsson, J., Sweden., &amp; Egeland, K.A. (2015). A Live Black-start Capability test of a Voltage Source HVDC Converter.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">Ying Jiang-Hafner, H. Duchen, M. Karlsson, L. Ronstrom and B. Abrahamsson, &quot;HVDC with voltage source converters - a powerful standby black start facility,&quot; <i>2008 IEEE/PES Transmission and Distribution Conference and Exposition</i>, Chicago, IL, USA, 2008, pp. 1-9, doi: 10.1109/TDC.2008.4517039.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">G. Li, C. Zhao, X. Zhang and G. Li, &quot;Research on &quot;Soft Start-up&quot; of VSC-HVDC in Power System Restoration after Blackouts,&quot; <i>2007 2nd IEEE Conference on Industrial Electronics and Applications</i>, Harbin, China, 2007, pp. 1939-1943, doi: 10.1109/ICIEA.2007.4318748.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">S. Li, M. Zhou, Z. Liu, J. Zhang and Y. Li, &quot;A study on VSC-HVDC based black start compared with traditional black start,&quot; <i>2009 International Conference on Sustainable Power Generation and Supply</i>, Nanjing, China, 2009, pp. 1-6, doi: 10.1109/SUPERGEN.2009.5348288.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">D. Lijun, G. Qi, L. Xuehua, L. Shuyong and H. Libin, &quot;Study of the VSC-HVDC Black Start Strategy Improvement Based on RTDS Closed Loop Simulation,&quot; <i>2018 International Conference on Power System Technology (POWERCON)</i>, Guangzhou, China, 2018, pp. 2622-2627, doi: 10.1109/POWERCON.2018.8601618.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt;\">N. Johannesson, T. Bogodorova and L. Vanfretti, &quot;Identifying low-order frequency-dependent transmission line model parameters,&quot; <i>2017 IEEE PES Innovative Smart Grid Technologies Conference Europe (ISGT-Europe)</i>, Turin, Italy, 2017, pp. 1-6, doi: 10.1109/ISGTEurope.2017.8260138.</span></li>
<li><span style=\"font-family: Arial; font-size: 9pt; color: #191919; background-color: #ffffff;\">L. Vanfretti and C. R. Laughman, &quot;Power System Modeling for Identification and Control Applications using Modelica and OpenIPSL,&quot; 2024 IEEE Conference on Control Technology and Applications (CCTA), Newcastle upon Tyne, United Kingdom, 2024, pp. 525-532, doi: 10.1109/CCTA60707.2024.10666594.</span></li>
</ol>
</html>"));
end Literature;
